// export const APP_URL = 'http://cofasv38/api/v2/eng'
export const APP_URL = 'https://dev.franklintn.gov/api/v2/eng'
export const APP_BASE = '/vesting'
export const APP_TITLE = 'Planning Department Project Vesting'
export const NODE_ENV: 'development' | 'test' | 'production' = 'production'