// export const APP_URL = 'http://cofasv38/api/v2/eng'
// export const LDAP_URL = 'http://cofasv38/api/v1/ldap'
export const APP_URL = 'https://dev.franklintn.gov/api/v2/eng'
export const LDAP_URL = 'https://dev.franklintn.gov/api/v1/ldap'
export const APP_BASE = '/vesting'
export const APP_TITLE = 'Planning Department Project Vesting'