export const API_URL = 'http://cofasv38/api/v1/eng'
// export const API_URL = 'https://dev.franklintn.gov/api/v1/eng'
// export const API_URL = 'http://cofasv30/api/v1/ldap'
export const LDAP_URL = 'http://cofasv38/api/v1/ldap'
export const APP_BASE = '/vesting'
export const APP_TITLE = 'Planning Department Project Vesting'